### ISSUE TITLE
Review item not opening

### ISSUE THREAD

**Issue by shiroyasha** [operately/operately#792]
I have a suspicious entry on the list (entry #3 on the screenshot):

a) It says that I'm the author of the check-in, and also the one who should review?
b) I get a 500 when I click on it

![Screenshot 2024-07-25 at 18 12 13](https://github.com/user-attachments/assets/b8640dba-5968-4396-8467-6e07901b0663)

**Comment by Rockyy174** [comment]
a) My first guess would be that you are the champion and the reviewer of the project. If that's not the case, I would have to investigate what is causing such a weird bug :expressionless:

b) Is it redirecting to the wrong place? Or is the page that it redirects to broken?

**Comment by shiroyasha** [comment]
a) Most likely yes, I'll have to dig deeper to figure this out
b) It is directing to https://app.operately.com/operately-0bcm/project-check-ins/2024-02-01-FDZHJeLLcOw7w1Di0bBrnM and then raises 500, which looks like the right place.

**Comment by shiroyasha** [comment]
This is what I get when I open the page:

```
operately-app-1  | 18:50:31.793 request_id=F-WJVUCAa0p7Aa0AAAtS [error] ** (FunctionClauseError) no function clause matching in Operately.Projects.Project.set_permissions/2
operately-app-1  | 18:50:31.795 request_id=F-WJVUCAa0p7Aa0AAAtS [error]     (operately 0.1.0) lib/operately/projects/project.ex:175: Operately.Projects.Project.set_permissions(nil, %Operately.People.Person{__meta__: #Ecto.Schema.Metadata<:loaded, "people">, id: "31781eb6-b889-440e-95ec-6258a6abb87c", account_id: "472edf66-eb66-46f8-85e5-0b9f17f30ac9", account: #Ecto.Association.NotLoaded<association :account is not loaded>, company_id: "24c23644-2afb-4d37-96e2-d4c3178ddc31", company: #Ecto.Association.NotLoaded<association :company is not loaded>, manager_id: nil, manager: #Ecto.Association.NotLoaded<association :manager is not loaded>, reports: #Ecto.Association.NotLoaded<association :reports is not loaded>, peers: nil, access_group: #Ecto.Association.NotLoaded<association :access_group is not loaded>, full_name: "Igor Šarčević", title: "Operately Co-Founder", avatar_url: "https://lh3.googleusercontent.com/a/ACg8ocILTOndcnZ-XIGfLdRiI4i6h2QhDVTtaj9XBh3FD_V94g8wLMo=s96-c", email: "igor@operately.com", timezone: "Europe/Belgrade", send_daily_summary: true, notify_on_mention: true, notify_about_assignments: true, theme: "light", company_role: :admin, suspended: false, suspended_at: nil, avatar_blob_id: "ebfef39f-b621-4ddd-ad34-f38c0f55dc65", has_open_invitation: false, inserted_at: ~N[2023-07-25 20:58:05], updated_at: ~N[2024-07-05 17:55:02]})
operately-app-1  |     (operately 0.1.0) lib/operately_web/api/queries/get_project_check_in.ex:59: OperatelyWeb.Api.Queries.GetProjectCheckIn.preload_project_permissions/2
operately-app-1  |     (operately 0.1.0) lib/operately_web/api/queries/get_project_check_in.ex:21: OperatelyWeb.Api.Queries.GetProjectCheckIn.call/2
operately-app-1  |     (operately 0.1.0) lib/turbo_connect/plugs/dispatch.ex:14: TurboConnect.Plugs.Dispatch.call/2
operately-app-1  |     (operately 0.1.0) lib/operately_web/api.ex:1: OperatelyWeb.Api.plug_builder_call/2
operately-app-1  |     (phoenix 1.7.12) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2
operately-app-1  |     (phoenix 1.7.12) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
operately-app-1  |     (operately 0.1.0) lib/operately_web/endpoint.ex:1: OperatelyWeb.Endpoint.plug_builder_call/2
```

**Comment by shiroyasha** [comment]
I think I've solved the mystery: The project is archived.

**Comment by Rockyy174** [comment]
Oh, I see. That explains why project is `nil` here:
`Operately.Projects.Project.set_permissions(nil, %Operately.People.Person...`

I guess the query doesn't return archived projects.
